name: learn-github-actions
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [master, develop]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 0.0.1-SNAPSHOT
          release_name: 0.0.1-SNAPSHOT
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
  notify:
    name: Notify to Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Notify stage 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "*Notify stage 1* **${{github.repository}}**: Release **${{ github.event.release.tag_name }}** published by **${{github.actor}}**"

      - name: Notify stage 2
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "*Notify stage 2* *${{github.repository}}*: Release *${{ github.event.release.tag_name }}* published by *${{github.actor}}*"