name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
  notify:
    name: Notify to Telegram
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Release notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "**${{github.repository}}**: Release **${{ github.event.release.tag_name }}** published by **${{github.actor}}**"