name: Release Tag
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 0.0.0-SNAPSHOT
          release_name: 0.0.0-SNAPSHOT
          body: |
            ## Changes in this Release
            - First Change
            - Second Change
            - Third Change ...
          draft: false
          prerelease: true
  notify:
    name: Notify to Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Release notification 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "*Notify 1* **${{github.repository}}**: Release **${{ github.event.release.tag_name }}** published by **${{github.actor}}**"

      - name: Release notification 2
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "*Notify 2* **${{github.repository}}**: Release **${{ github.event.release.tag_name }}** published by **${{github.actor}}**"